
import React, { useEffect, useState } from 'react';
import { UserProfile, GloryInsight } from '../types';
import { getGloryScroll } from '../services/geminiService';

interface GloryScrollProps {
  profile: UserProfile;
}

const GloryScroll: React.FC<GloryScrollProps> = ({ profile }) => {
  const [scrollData, setScrollData] = useState<GloryInsight[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getGloryScroll(profile.name)
      .then(setScrollData)
      .catch(() => setScrollData([]))
      .finally(() => setLoading(false));
  }, [profile.name]);

  return (
    <div className="space-y-10 pb-24 animate-enter max-w-3xl mx-auto">
      <header className="text-center space-y-4 px-4">
        <div className="inline-flex items-center gap-2 bg-amber-500/10 px-4 py-1.5 rounded-full border border-amber-500/20">
          <span className="w-2 h-2 bg-amber-400 rounded-full animate-ping"></span>
          <span className="text-[10px] font-black text-amber-300 uppercase tracking-[0.3em]">Phase 3: Prophetic Flow</span>
        </div>
        <h2 className="text-4xl md:text-6xl serif italic font-bold text-white text-glow-amber">The Glory Scrolls</h2>
        <p className="text-sm md:text-base text-white/50 max-w-xl mx-auto leading-relaxed">
          Prophetic resonance tailored for your career, spiritual walk, and marketplace impact. Generated by the Spirit of Counsel.
        </p>
      </header>

      <div className="grid grid-cols-1 gap-8 px-4">
        {loading ? (
          Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="glass h-64 animate-pulse bg-white/5 border-white/5" />
          ))
        ) : scrollData.length > 0 ? (
          scrollData.map((item, idx) => (
            <div 
              key={idx} 
              className={`glass p-10 md:p-14 relative overflow-hidden group hover:bg-white/5 transition-all border-l-8 shadow-2xl ${
                item.category === 'WORD' ? 'border-amber-500' : 
                item.category === 'WALK' ? 'border-green-500' : 
                'border-indigo-500'
              }`}
            >
              <div className="relative z-10 space-y-6">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-black uppercase tracking-widest opacity-60 px-3 py-1 bg-white/5 rounded-full">{item.category} MANIFESTATION</span>
                  <div className="h-px flex-1 mx-6 bg-white/10 hidden md:block"></div>
                  <span className="text-xs font-bold text-amber-400 tracking-tighter">{item.verse}</span>
                </div>
                <h4 className="text-3xl md:text-5xl serif font-bold text-white leading-tight">{item.title}</h4>
                <p className="text-lg md:text-xl text-white/70 leading-relaxed font-serif italic border-l-2 border-white/10 pl-6">
                  "{item.content}"
                </p>
              </div>
              {/* Decorative faint icon */}
              <div className="absolute top-8 right-8 text-8xl opacity-[0.03] select-none pointer-events-none group-hover:scale-125 transition-transform duration-1000">
                {item.category === 'WORD' ? '📜' : item.category === 'WALK' ? '👣' : '🪙'}
              </div>
            </div>
          ))
        ) : (
          <div className="glass p-20 text-center opacity-40">
            <span className="text-6xl block mb-6">🕯️</span>
            <p className="text-lg italic serif">Synchronizing the heavenly archives... please check your connection.</p>
          </div>
        )}
      </div>

      <footer className="text-center opacity-20 py-10">
        <p className="text-[10px] font-black uppercase tracking-[0.5em]">Lumina Shekinah v0.5.0-STABLE</p>
      </footer>
    </div>
  );
};

export default GloryScroll;
